### ISSUE TITLE
StackOverflowException when mapping T with a property List<T>

### ISSUE THREAD

**Issue by sergiorykov** [TinyMapper/TinyMapper#33]
```
public class NestedPoco : SimplePoco
    {
        public List<NestedPoco> NestedObjects { get; set; }

        public NestedPoco()
        {
            NestedObjects = new List<NestedPoco>();
        }
    }
```

Mapping

```
TinyMapper.Bind<NestedPoco, NestedPocoDTO>(config =>
{
       config.Bind(target => target.NestedObjects, typeof(List<NestedPoco>));
});
```

Sample from https://github.com/lusocoding/dotnet-objmap-benchmark/blob/master/Obj2ObjMapBench/Models/NestedPoco.cs

https://github.com/lusocoding/dotnet-objmap-benchmark/issues/1

**Comment by GSerjo** [comment]
thanks!

fixed https://github.com/TinyMapper/TinyMapper/releases/tag/v2.1.4-bet

**Comment by nzaugg** [comment]
Sergey,

I have noticed some problems with the 2.1.4-beta we have out on NuGet right
now. Auto Mapping (without calling bind) has been removed completely with
no option to re-enable. While this may be an intentional design
decision, Semantic
Versioning <http://semver.org/> rules would indicate that we would need to
make this at least a 3.0 release instead.

Although I think that the auto mapping feature can cause trouble (mostly
when dealing with proxy objects), I think it's a feature we should retain.
It's just so handy in so many other places.

Just a thought. Noticed a bunch of code was broken this week because we
updated to the latest.

Thanks!
Nate Zaugg

nzaugg@gmail.com

**Comment by GSerjo** [comment]
yeah, you're right, sorry about that. Yes, I've removed it for a reason, the main idea does not add `lock`  for internal mappers dictionary. Let me briefly describe the mapping process, it would be a bit clear why this feature has been removed

- During `Bind` TinyMapper creates a Mapper and put it to the `dictionary`
- During `Map` the dictionary is used to lookup the `mapper` but in the previous version `Map` method updated the dictionary. 

It's fine until `Map` is used in the multi-threaded environment. 

You can simulate this behavior but you should use a wrapper around a `TinyMapper`. For instance, I try to create a wrapper around the third party libraries, it gives the ability to migrate to another library without a big effort. I don't create a wrapper for all third-party libraries, only for some of them. 

I'll republish the nuget package and update version.  Thank you for the feedback, I appreciate it.
