### ISSUE TITLE
Should I call Bind for Map?

### ISSUE THREAD

**Issue by iamkarlson** [TinyMapper/TinyMapper#59]
In #48 your answered second question but not first. What is a proper way to use TinyMapper? Should I call **Bind** for each different **Map** call? For example, one exact type to another exact type **Map** is called 5-6 times throughout application, but I don't call **Bind** at all. Is it ok? If I don't call bind at all, how will it affect app's performance?

**Comment by GSerjo** [comment]
sorry, my fault.

Let me briefly describe what each method does, it makes the below answer a bit more clear.
`Bind` - generate mapping code, almost similar to handwritten. it's the most time-consuming part and has to be called once. The generated code is cached.
`Map` - just executes code created by `Bind` method, but if the Bind was not called, `Map` internally will call `Bind` and then `Map`.

>Should I call Bind for each different Map call?

Yes, it preferably

> I don't call Bind at all. Is it ok?

Yes, for `2.0.8` and less. 

>I don't call bind at all, how will it affect app's performance?

Absolutely the same, i.e. `Bind` + `Map` = `Map`, i.e. if Bind was not called then `Map` will call it only once.

**Note:** If don't call a `Bind` in advance and execute `Map` method in parallel it's a potential issue because `TinyMapper` doesn't lock internal dictionary. If the app works in a single thread or call Bind in advance it's okay to call `Map` in parallel

**Comment by iamkarlson** [comment]
Great answer! Thanks!
